"Resource/UI/ItemModelPanel.res"
{
	"Disguising"
	{
		"ControlName"	"Label"
		"fieldName"		"Disguising"
		"font"			"Size 12"
		"xpos"			"cs-0.5"
		"ypos"			"c90"
		"zpos"			"2"
		"wide"			"60"
		"tall"			"10"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"Disguising..."
		"textAlignment"		"center"
		"fgcolor_override"		"White"
	}

	"DisguisingShadow"
	{
		"ControlName"	"Label"
		"fieldName"		"DisguisingShadow"
		"font"			"Size 12"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"Disguising..."
		"textAlignment"		"center"
		"fgcolor_override"		"Shadow"

		"pin_to_sibling"		"Disguising"
	}

	"DisguiseStatusBG"
	{
		"ControlName"				"CTFImagePanel"
		"fieldName"					"DisguiseStatusBG"
		"xpos"						"0"
		"ypos"						"-23"
		"zpos"						"1"
		"wide"						"160"
		"tall"	 					"2"
		"autoResize"				"0"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"image"						"replay/thumbnails/panels/black"
		"scaleImage"				"1"
		"teambg_1"					"replay/thumbnails/panels/black"
		"teambg_2"					"replay/thumbnails/panels/red"
		"teambg_3"					"replay/thumbnails/panels/blue"
		
		"src_corner_height"			"32"
		"src_corner_width"			"32"
		
		"draw_corner_width"			"0"
		"draw_corner_height" 		"0"
		
		"pin_to_sibling"			"Background"
	}
	
	"Background"
	{
		"ControlName"				"EditablePanel"
		"fieldName"					"Background"
		"xpos"						"85"
		"ypos"						"r25"
		"zpos"						"0"
		"wide"						"160"
		"tall"	 					"25"
		"autoResize"				"0"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"paintbackground"			"1"
		"paintbackgroundtype"		"0"
		"bgcolor_override"			"TransparentBlack"
	}
	
	"Separator"
	{
		"ControlName"				"EditablePanel"
		"fieldName"					"Separator"
		"xpos"						"-35"
		"ypos"						"-2"
		"zpos"						"10"
		"wide"						"1"
		"tall"	 					"19"
		"autoResize"				"0"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"paintbackground"			"1"
		"paintbackgroundtype"		"0"
		"bgcolor_override"			"White"
		
		"pin_to_sibling"			"Background"
	}

	"DisguiseNameLabel"
	{	
		"ControlName"				"Label"
		"fieldName"					"DisguiseNameLabel"
		"font"						"Size 11"
		"xpos"						"-43"
		"ypos"						"0"
		"zpos"						"10"
		"wide"						"110"
		"tall"						"14"
		"autoResize"				"0"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"%disguisename%"
		"textAlignment"				"West"
		"dulltext"					"0"
		"brighttext"				"0"
		"fgcolor_override"			"White"
		
		"pin_to_sibling"			"Background"
	}
	
	"WeaponNameLabel"
	{	
		"ControlName"				"Label"
		"fieldName"					"WeaponNameLabel"
		"font"						"Size 11"
		"xpos"						"0"
		"ypos"						"-10"
		"zpos"						"10"
		"wide"						"110"
		"tall"						"14"
		"autoResize"				"0"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"%weaponname%"
		"textAlignment"				"West"
		"dulltext"					"0"
		"brighttext"				"0"
		"fgcolor_override"			"White"
		
		"pin_to_sibling"			"DisguiseNameLabel"
	}
	
	"SpectatorGUIHealth"
	{
		"ControlName"				"EditablePanel"
		"fieldName"					"SpectatorGUIHealth"
		"xpos"						"34"
		"ypos"						"1"
		"wide"						"32"
		"tall"						"21"
		"zpos"						"10"
		"visible"					"1"
		"enabled"					"1"
		"HealthBonusPosAdj"			"10"
		"HealthDeathWarning"		"0.49"
		"TFFont"					"Size 16"
		"HealthDeathWarningColor"	"Low Health"
		"TextColor"					"HudOffWhite"

		"pin_to_sibling"			"Separator"
	}
}
